env:
  - CGO_ENABLED=0
builds:
  - goos:
      - linux
      - darwin
      - freebsd
      - netbsd
      - openbsd
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
archives:
  - id: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    files:
      - none*
changelog:
  skip: true
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
release:
  github:
    owner: nmoutschen
    name: test-goreleaser
  name_template: "Version {{ .Version }}"
snapshot:
  name_template: "{{ .Tag }}-dev"